name: CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    strategy:
      matrix:
        environment: [prod]
    environment:
      name: ${{ matrix.environment }}
      url: https://localhost/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "this environment is ${{ matrix.environment }}"
